name: First workflow
on: push
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
       - name: Print Greeting
         run: echo "!Hello Morning Mano!"     
  secondjob:
     runs-on: ubuntu-latest
     steps:
        - name: Print GoodBye
          run: echo "${{ toJSON(github) }}"
